### PR TITLE
Enforce C style

### PR DESCRIPTION
**Pull request by vhotspur**
Convert to a unified C style (enforcing new rules in each commit) with CI-enforced checks.

Changes applied and enforced:

* Unix endings (LF, EOF) and UTF-8 only
* space-only indentation
* braces around single-line statements (always)
* `#include`s sorted

### CODE REVIEW

**Comment by lbulej** [comment]
Can I play with `.clang-format` settings too? :-)

**Comment by vhotspur** [comment]
> Can I play with `.clang-format` settings too? :-)

Are you in such hurry? I still have some stashed changes and I am adding the rules slowly so that I can still reasonably review that the automated formatting have not broken anything.

And no, there will be no spaces in function calls ;-).

**Comment by lbulej** [comment]
> > Can I play with `.clang-format` settings too? :-)
> 
> Are you in such hurry? I still have some stashed changes and I am adding the rules slowly so that I can still reasonably review that the automated formatting have not broken anything.

Not really in hurry. I'm just asking for general permission to potentially chime in, because I don't like how clang formats some of the things :-)

> And no, there will be no spaces in function calls ;-).

I would not dare... :-)

**Comment by HanyzPAPU** [comment]
I’m curious about how this change will handle some of the uglier parts of the code I’ve written (mostly the parts with C macros). Perhaps it would be better to refactor these part so they are written more reasonably.

**Comment by lbulej** [comment]
> I’m curious about how this change will handle some of the uglier parts of the code I’ve written (mostly the parts with C macros). Perhaps it would be better to refactor these part so they are written more reasonably.

That's the plan after we clean up/unify/enforce formatting, so that refactoring is not mixed up with formatting changes.

**Comment by vhotspur** [comment]
> I'm just asking for general permission to potentially chime in because I don't like how clang formats some of the things :-)

Now is the right time :-).

I think I have covered the most offensive parts (at least for me) and now the C style is enforced so things will only improve™.

Summary of changes

  * Unix endings (LF, EOF) and UTF-8 only
  * space-only indentation
  * braces around single-line statements (always)
  * `#include`s sorted

I would like to merge this before any further (functional) changes are made to prevent conflicts.

**Pull request merged**
