### PR TITLE
Add XCRV instruction for dumping CP0 registers

### PR DESCRIPTION
**Pull request by vhotspur**
Add a special instruction that prints contents of CP0 registers.

Thus, it is possible to print all CPU registers with following two instructions:

```asm
.word 0x37
.word 0x0e
```

### CODE REVIEW

**Comment by ceresek** [comment]
Just how do we choose the opcodes ? :-)

**Review by ceresek — APPROVED** [review]

**Comment by vhotspur** [comment]
Just by finding unused instructions.

Perhaps next time this could be split into two pull requests as ExCode description is orthogonal to this.

**Comment by ceresek** [comment]
Sure :) so, merge, or, split and merge, or ?

**Comment by vhotspur** [comment]
Hopefully rebased correctly. Thanks!

**Pull request merged**
